// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DataAccess;

namespace DataAccess.Migrations
{
    [DbContext(typeof(MoneyManagerContext))]
    [Migration("20200401132411_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23dcddec-ea26-4ac2-a0f0-4ee19293d71c"),
                            Name = "Q7ZC1NN",
                            UserId = new Guid("12e7dc3a-1b52-4811-a848-1e748168db53")
                        },
                        new
                        {
                            Id = new Guid("ca8d21c5-e52f-4332-a334-1cf88f33c8ad"),
                            Name = "7QB45WO",
                            UserId = new Guid("0c072651-0a8c-4819-82be-03f91183934e")
                        },
                        new
                        {
                            Id = new Guid("e8138054-fa82-41d6-8151-a0beae0e9ce3"),
                            Name = "XYO6E9B",
                            UserId = new Guid("093d4313-7992-42f6-85c3-8a15e3ccbd2b")
                        },
                        new
                        {
                            Id = new Guid("9ae88eb3-6566-4bc9-a324-d2f02be4fe97"),
                            Name = "NW9L5Q0",
                            UserId = new Guid("10a43690-3d99-48bf-894a-2fbdc4296ad8")
                        },
                        new
                        {
                            Id = new Guid("11f8fdde-907b-4789-bfc4-4c957863cf08"),
                            Name = "9CYIGU4",
                            UserId = new Guid("e68808ab-20fa-4191-ad88-f662ec6fb9da")
                        },
                        new
                        {
                            Id = new Guid("bc4e06fe-7a90-4b59-958a-1c3c1aebe354"),
                            Name = "ZWH188J",
                            UserId = new Guid("12e7dc3a-1b52-4811-a848-1e748168db53")
                        },
                        new
                        {
                            Id = new Guid("ae4ca653-cc94-4b79-90f6-3cd3da759bf7"),
                            Name = "PWRWZUR",
                            UserId = new Guid("0c072651-0a8c-4819-82be-03f91183934e")
                        },
                        new
                        {
                            Id = new Guid("ecceeaed-787c-4750-bb40-f5d517e5c3db"),
                            Name = "DK1SB3F",
                            UserId = new Guid("093d4313-7992-42f6-85c3-8a15e3ccbd2b")
                        },
                        new
                        {
                            Id = new Guid("c34312b6-0d0f-4ef7-b41f-dc8452416b69"),
                            Name = "K8FHF40",
                            UserId = new Guid("10a43690-3d99-48bf-894a-2fbdc4296ad8")
                        },
                        new
                        {
                            Id = new Guid("df8a6e5e-f402-462b-976c-9d307ec12ee7"),
                            Name = "MMVM71M",
                            UserId = new Guid("e68808ab-20fa-4191-ad88-f662ec6fb9da")
                        },
                        new
                        {
                            Id = new Guid("69c6d469-00f8-4f28-9f04-f7e17df4f5f7"),
                            Name = "R4ZVJ5X",
                            UserId = new Guid("12e7dc3a-1b52-4811-a848-1e748168db53")
                        },
                        new
                        {
                            Id = new Guid("78c7348d-88ff-41f0-8259-0d97675a5f9c"),
                            Name = "RNHNM83",
                            UserId = new Guid("0c072651-0a8c-4819-82be-03f91183934e")
                        },
                        new
                        {
                            Id = new Guid("e9ccf1cd-714a-405e-bf7d-4924693e80fb"),
                            Name = "2RPHVLI",
                            UserId = new Guid("093d4313-7992-42f6-85c3-8a15e3ccbd2b")
                        },
                        new
                        {
                            Id = new Guid("7aae3717-f242-43b2-a74a-50dc23a1b355"),
                            Name = "7K4J545",
                            UserId = new Guid("10a43690-3d99-48bf-894a-2fbdc4296ad8")
                        },
                        new
                        {
                            Id = new Guid("f3583cf4-e20f-4eae-8740-e47074979b1d"),
                            Name = "LG5KM7S",
                            UserId = new Guid("e68808ab-20fa-4191-ad88-f662ec6fb9da")
                        },
                        new
                        {
                            Id = new Guid("0ea9e1f1-4c0c-4bfa-875a-d31750df7414"),
                            Name = "8B8OP60",
                            UserId = new Guid("12e7dc3a-1b52-4811-a848-1e748168db53")
                        },
                        new
                        {
                            Id = new Guid("83a5f742-d236-4dae-8aad-74ad63af0433"),
                            Name = "D8V5OYG",
                            UserId = new Guid("0c072651-0a8c-4819-82be-03f91183934e")
                        },
                        new
                        {
                            Id = new Guid("1180a574-d677-49e9-9109-bc5492e60ca4"),
                            Name = "RBX40PJ",
                            UserId = new Guid("093d4313-7992-42f6-85c3-8a15e3ccbd2b")
                        },
                        new
                        {
                            Id = new Guid("7245285b-415c-497f-8e05-46601832d5a6"),
                            Name = "FWYL16D",
                            UserId = new Guid("10a43690-3d99-48bf-894a-2fbdc4296ad8")
                        },
                        new
                        {
                            Id = new Guid("91d62eae-5a19-406f-914d-84feb1e5f182"),
                            Name = "Q4AL63U",
                            UserId = new Guid("e68808ab-20fa-4191-ad88-f662ec6fb9da")
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Name = "IVW3WG4",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Name = "4MWTC6C",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Name = "6AD4L8L",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Name = "H2CA6CC",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Name = "V2QAPRS",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Name = "ZRVY3CN",
                            ParentId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Name = "XVH5BJR",
                            ParentId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Name = "W4H5Y0N",
                            ParentId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Name = "SORASTL",
                            ParentId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Name = "XL4OEW3",
                            ParentId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Type = 0
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(16,3)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(1024)")
                        .HasMaxLength(1024);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2e3eac2-11cd-4eb7-992b-e5816f2a8cf0"),
                            Amount = 0.0299506141012304m,
                            AssetId = new Guid("23dcddec-ea26-4ac2-a0f0-4ee19293d71c"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 382, DateTimeKind.Local).AddTicks(393)
                        },
                        new
                        {
                            Id = new Guid("054c2647-001c-4d78-9653-5e72699d09ef"),
                            Amount = 0.505493903302352m,
                            AssetId = new Guid("ca8d21c5-e52f-4332-a334-1cf88f33c8ad"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(4839)
                        },
                        new
                        {
                            Id = new Guid("4bc878ab-911e-423a-afc2-f0ec075fd409"),
                            Amount = 0.227213436843461m,
                            AssetId = new Guid("e8138054-fa82-41d6-8151-a0beae0e9ce3"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(4894)
                        },
                        new
                        {
                            Id = new Guid("c7eaac8c-9a8e-477c-9c7f-445679b36eb6"),
                            Amount = 0.32080914514177m,
                            AssetId = new Guid("9ae88eb3-6566-4bc9-a324-d2f02be4fe97"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(4919)
                        },
                        new
                        {
                            Id = new Guid("a07999a7-ada9-4d4b-84e1-b4cd8d0ac7b7"),
                            Amount = 0.551171180583151m,
                            AssetId = new Guid("11f8fdde-907b-4789-bfc4-4c957863cf08"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(4940)
                        },
                        new
                        {
                            Id = new Guid("3fd2b360-5969-461f-a67e-a47edacc0b48"),
                            Amount = 0.862305555894182m,
                            AssetId = new Guid("bc4e06fe-7a90-4b59-958a-1c3c1aebe354"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(4976)
                        },
                        new
                        {
                            Id = new Guid("e59d4710-991c-44a4-a773-91ddbb274868"),
                            Amount = 0.00547851855190402m,
                            AssetId = new Guid("ae4ca653-cc94-4b79-90f6-3cd3da759bf7"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(4997)
                        },
                        new
                        {
                            Id = new Guid("fb63b691-b2d1-4a20-867f-00acd8724e00"),
                            Amount = 0.971693047774813m,
                            AssetId = new Guid("ecceeaed-787c-4750-bb40-f5d517e5c3db"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5018)
                        },
                        new
                        {
                            Id = new Guid("c17298a4-7bf3-4fea-b171-dbea1fc4bb40"),
                            Amount = 0.576904108085159m,
                            AssetId = new Guid("c34312b6-0d0f-4ef7-b41f-dc8452416b69"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5039)
                        },
                        new
                        {
                            Id = new Guid("93c94f0c-a7ab-457d-80c5-3d9fd14bdde4"),
                            Amount = 0.729424388021894m,
                            AssetId = new Guid("df8a6e5e-f402-462b-976c-9d307ec12ee7"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5060)
                        },
                        new
                        {
                            Id = new Guid("7d1983a5-b178-4d79-9645-ac469c3011c7"),
                            Amount = 0.987133041949539m,
                            AssetId = new Guid("69c6d469-00f8-4f28-9f04-f7e17df4f5f7"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5081)
                        },
                        new
                        {
                            Id = new Guid("dec247cf-d4e7-4f4a-aef5-66284c64a5ed"),
                            Amount = 0.89461384243081m,
                            AssetId = new Guid("78c7348d-88ff-41f0-8259-0d97675a5f9c"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5115)
                        },
                        new
                        {
                            Id = new Guid("80a938e7-5176-4ee2-8fc8-0915741ff54d"),
                            Amount = 0.695734268378343m,
                            AssetId = new Guid("e9ccf1cd-714a-405e-bf7d-4924693e80fb"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5135)
                        },
                        new
                        {
                            Id = new Guid("42982135-d98b-4e0e-93cd-98c28ac9e6e7"),
                            Amount = 0.86153335723166m,
                            AssetId = new Guid("7aae3717-f242-43b2-a74a-50dc23a1b355"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5159)
                        },
                        new
                        {
                            Id = new Guid("7f545a56-3ead-4f88-998d-30b7ded096e9"),
                            Amount = 0.221420383183947m,
                            AssetId = new Guid("f3583cf4-e20f-4eae-8740-e47074979b1d"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5178)
                        },
                        new
                        {
                            Id = new Guid("2d0a2e38-1e17-4b42-9678-f6e51bac9c45"),
                            Amount = 0.562892019545143m,
                            AssetId = new Guid("0ea9e1f1-4c0c-4bfa-875a-d31750df7414"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5198)
                        },
                        new
                        {
                            Id = new Guid("8192b804-4438-4f9b-bba4-a5b038e30869"),
                            Amount = 0.774823381460655m,
                            AssetId = new Guid("83a5f742-d236-4dae-8aad-74ad63af0433"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5218)
                        },
                        new
                        {
                            Id = new Guid("005ef2ba-404f-4946-80dd-2169efaec089"),
                            Amount = 0.557433252482411m,
                            AssetId = new Guid("1180a574-d677-49e9-9109-bc5492e60ca4"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5238)
                        },
                        new
                        {
                            Id = new Guid("bd1822df-bbb0-4955-81cd-83cc0e13a428"),
                            Amount = 0.594198351071309m,
                            AssetId = new Guid("7245285b-415c-497f-8e05-46601832d5a6"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5257)
                        },
                        new
                        {
                            Id = new Guid("56c0876d-cbd2-48b4-9d36-a067a187d83e"),
                            Amount = 0.0253863642110426m,
                            AssetId = new Guid("91d62eae-5a19-406f-914d-84feb1e5f182"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5278)
                        },
                        new
                        {
                            Id = new Guid("a7018c09-c235-4af9-bd07-6b9929c512cd"),
                            Amount = 0.544164116282092m,
                            AssetId = new Guid("23dcddec-ea26-4ac2-a0f0-4ee19293d71c"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5299)
                        },
                        new
                        {
                            Id = new Guid("4b15986a-10ad-4a48-a284-5fe5e052c89c"),
                            Amount = 0.802730774415066m,
                            AssetId = new Guid("ca8d21c5-e52f-4332-a334-1cf88f33c8ad"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5322)
                        },
                        new
                        {
                            Id = new Guid("c8d5b667-e44d-47ba-85b5-b8cb4296ef7a"),
                            Amount = 0.413952119375557m,
                            AssetId = new Guid("e8138054-fa82-41d6-8151-a0beae0e9ce3"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5343)
                        },
                        new
                        {
                            Id = new Guid("f5487ad3-0d03-4d36-8b51-9e187fbf08ea"),
                            Amount = 0.194135709290456m,
                            AssetId = new Guid("9ae88eb3-6566-4bc9-a324-d2f02be4fe97"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5363)
                        },
                        new
                        {
                            Id = new Guid("59d82998-5986-4300-a575-e138cfeacce1"),
                            Amount = 0.90073975916055m,
                            AssetId = new Guid("11f8fdde-907b-4789-bfc4-4c957863cf08"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5382)
                        },
                        new
                        {
                            Id = new Guid("c95aab66-d691-497f-ace8-5fdfa696e0cc"),
                            Amount = 0.230678658574204m,
                            AssetId = new Guid("bc4e06fe-7a90-4b59-958a-1c3c1aebe354"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5401)
                        },
                        new
                        {
                            Id = new Guid("05716cec-d194-470d-af5f-2c2b77808394"),
                            Amount = 0.935574950620334m,
                            AssetId = new Guid("ae4ca653-cc94-4b79-90f6-3cd3da759bf7"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5421)
                        },
                        new
                        {
                            Id = new Guid("06a936c5-a383-44b7-adde-244f8774dca5"),
                            Amount = 0.250470375293154m,
                            AssetId = new Guid("ecceeaed-787c-4750-bb40-f5d517e5c3db"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5441)
                        },
                        new
                        {
                            Id = new Guid("aa7d25e6-b792-452a-83e3-30f877c25e83"),
                            Amount = 0.876170352043663m,
                            AssetId = new Guid("c34312b6-0d0f-4ef7-b41f-dc8452416b69"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5461)
                        },
                        new
                        {
                            Id = new Guid("9193aa5e-27ce-436d-996a-d451dcc34999"),
                            Amount = 0.36667112138433m,
                            AssetId = new Guid("df8a6e5e-f402-462b-976c-9d307ec12ee7"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5483)
                        },
                        new
                        {
                            Id = new Guid("5a22ab31-b39a-4890-8385-54807f7f63ec"),
                            Amount = 0.558213454465481m,
                            AssetId = new Guid("69c6d469-00f8-4f28-9f04-f7e17df4f5f7"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5503)
                        },
                        new
                        {
                            Id = new Guid("88f137c9-cdaa-4bb3-a53a-ee5d6caa3ecf"),
                            Amount = 0.589283811668532m,
                            AssetId = new Guid("78c7348d-88ff-41f0-8259-0d97675a5f9c"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5522)
                        },
                        new
                        {
                            Id = new Guid("e56fb071-9782-4fa8-9eb2-c2b37afe2b7d"),
                            Amount = 0.985820349764926m,
                            AssetId = new Guid("e9ccf1cd-714a-405e-bf7d-4924693e80fb"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5548)
                        },
                        new
                        {
                            Id = new Guid("9bb944db-b2c7-4466-9dfb-296206deb9df"),
                            Amount = 0.996931511907341m,
                            AssetId = new Guid("7aae3717-f242-43b2-a74a-50dc23a1b355"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5569)
                        },
                        new
                        {
                            Id = new Guid("358634f9-be26-4b22-8b66-b8de2e2908f2"),
                            Amount = 0.00918711722324934m,
                            AssetId = new Guid("f3583cf4-e20f-4eae-8740-e47074979b1d"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5589)
                        },
                        new
                        {
                            Id = new Guid("05e0b60c-e516-4f35-a131-37a7fcf42569"),
                            Amount = 0.191899084575427m,
                            AssetId = new Guid("0ea9e1f1-4c0c-4bfa-875a-d31750df7414"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5608)
                        },
                        new
                        {
                            Id = new Guid("fd9f939f-84ca-463d-9015-829f74c9617c"),
                            Amount = 0.598562804329471m,
                            AssetId = new Guid("83a5f742-d236-4dae-8aad-74ad63af0433"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5627)
                        },
                        new
                        {
                            Id = new Guid("05f55b52-db91-4faa-8b69-82fbc1b02a3a"),
                            Amount = 0.897685491432289m,
                            AssetId = new Guid("1180a574-d677-49e9-9109-bc5492e60ca4"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5649)
                        },
                        new
                        {
                            Id = new Guid("27003c64-30a5-469c-a027-ce09a957d5ed"),
                            Amount = 0.339487810777262m,
                            AssetId = new Guid("7245285b-415c-497f-8e05-46601832d5a6"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5669)
                        },
                        new
                        {
                            Id = new Guid("f9fb14f8-66ab-4a98-9d54-0cba77b73513"),
                            Amount = 0.323947774862846m,
                            AssetId = new Guid("91d62eae-5a19-406f-914d-84feb1e5f182"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5688)
                        },
                        new
                        {
                            Id = new Guid("70e522fb-2c97-46cd-882e-d2fdd162f48d"),
                            Amount = 0.964572537208242m,
                            AssetId = new Guid("23dcddec-ea26-4ac2-a0f0-4ee19293d71c"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5709)
                        },
                        new
                        {
                            Id = new Guid("74926ee6-8fdf-4fd3-b867-fdc63fae090a"),
                            Amount = 0.382168749990952m,
                            AssetId = new Guid("ca8d21c5-e52f-4332-a334-1cf88f33c8ad"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5728)
                        },
                        new
                        {
                            Id = new Guid("55f0a296-d148-43b1-8cb6-6c3cbdb1c1c8"),
                            Amount = 0.000725552440027498m,
                            AssetId = new Guid("e8138054-fa82-41d6-8151-a0beae0e9ce3"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5747)
                        },
                        new
                        {
                            Id = new Guid("b19f18c6-5347-4150-a45d-009ad1a3dbec"),
                            Amount = 0.972879442839361m,
                            AssetId = new Guid("9ae88eb3-6566-4bc9-a324-d2f02be4fe97"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5766)
                        },
                        new
                        {
                            Id = new Guid("e001fafc-69e3-43da-8f6a-caccdc620523"),
                            Amount = 0.640175224114291m,
                            AssetId = new Guid("11f8fdde-907b-4789-bfc4-4c957863cf08"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5785)
                        },
                        new
                        {
                            Id = new Guid("5d4aaf65-38cc-4160-9590-8179ba22a097"),
                            Amount = 0.636413871141343m,
                            AssetId = new Guid("bc4e06fe-7a90-4b59-958a-1c3c1aebe354"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5808)
                        },
                        new
                        {
                            Id = new Guid("dc831135-5d8a-4437-bf0f-8ab02b9121b9"),
                            Amount = 0.234462475047662m,
                            AssetId = new Guid("ae4ca653-cc94-4b79-90f6-3cd3da759bf7"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5828)
                        },
                        new
                        {
                            Id = new Guid("78be4070-7534-470a-b01d-22f9565b9094"),
                            Amount = 0.089711253107391m,
                            AssetId = new Guid("ecceeaed-787c-4750-bb40-f5d517e5c3db"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5849)
                        },
                        new
                        {
                            Id = new Guid("c18dc8e1-c00f-4a44-8214-2772d8713694"),
                            Amount = 0.0884600771071669m,
                            AssetId = new Guid("c34312b6-0d0f-4ef7-b41f-dc8452416b69"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5869)
                        },
                        new
                        {
                            Id = new Guid("57642168-a2cf-44ea-bd17-67f0ccee158e"),
                            Amount = 0.300216242810812m,
                            AssetId = new Guid("df8a6e5e-f402-462b-976c-9d307ec12ee7"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5890)
                        },
                        new
                        {
                            Id = new Guid("6fac3535-963e-4bff-84d9-0ad03e6bf85e"),
                            Amount = 0.656312388207909m,
                            AssetId = new Guid("69c6d469-00f8-4f28-9f04-f7e17df4f5f7"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5909)
                        },
                        new
                        {
                            Id = new Guid("ce6ef68a-430d-412b-a888-177d4f02c44c"),
                            Amount = 0.831220396715785m,
                            AssetId = new Guid("78c7348d-88ff-41f0-8259-0d97675a5f9c"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5929)
                        },
                        new
                        {
                            Id = new Guid("4e860fa5-5598-4647-9716-3930f0b5cef7"),
                            Amount = 0.747592647908066m,
                            AssetId = new Guid("e9ccf1cd-714a-405e-bf7d-4924693e80fb"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5950)
                        },
                        new
                        {
                            Id = new Guid("286daf36-cabf-4281-9059-89f8fe09514a"),
                            Amount = 0.2269078601277m,
                            AssetId = new Guid("7aae3717-f242-43b2-a74a-50dc23a1b355"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5973)
                        },
                        new
                        {
                            Id = new Guid("d2249b9c-1be8-4713-8d65-b3a1b123bf3a"),
                            Amount = 0.837867657578489m,
                            AssetId = new Guid("f3583cf4-e20f-4eae-8740-e47074979b1d"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(5998)
                        },
                        new
                        {
                            Id = new Guid("869c1ff4-7586-4e1e-9604-1a716538aa74"),
                            Amount = 0.953463109654124m,
                            AssetId = new Guid("0ea9e1f1-4c0c-4bfa-875a-d31750df7414"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6017)
                        },
                        new
                        {
                            Id = new Guid("eee84f62-4d45-435f-888b-22f4669f3312"),
                            Amount = 0.817785053894755m,
                            AssetId = new Guid("83a5f742-d236-4dae-8aad-74ad63af0433"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6037)
                        },
                        new
                        {
                            Id = new Guid("88369920-ee45-4a36-b234-d0a3b99f8623"),
                            Amount = 0.759320997520965m,
                            AssetId = new Guid("1180a574-d677-49e9-9109-bc5492e60ca4"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6058)
                        },
                        new
                        {
                            Id = new Guid("d48d6e2e-757a-4816-9423-bbdedaac8298"),
                            Amount = 0.146312655949179m,
                            AssetId = new Guid("7245285b-415c-497f-8e05-46601832d5a6"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6078)
                        },
                        new
                        {
                            Id = new Guid("8905f7a5-9540-46ec-96ee-36ea2deb9e01"),
                            Amount = 0.0467357919769063m,
                            AssetId = new Guid("91d62eae-5a19-406f-914d-84feb1e5f182"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6096)
                        },
                        new
                        {
                            Id = new Guid("1a019f25-6525-4f89-b430-0f06681c4b6b"),
                            Amount = 0.652973875241808m,
                            AssetId = new Guid("23dcddec-ea26-4ac2-a0f0-4ee19293d71c"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6116)
                        },
                        new
                        {
                            Id = new Guid("1a14bd80-6d6b-462f-a903-bafc2b8d2756"),
                            Amount = 0.48125141322671m,
                            AssetId = new Guid("ca8d21c5-e52f-4332-a334-1cf88f33c8ad"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6139)
                        },
                        new
                        {
                            Id = new Guid("c47fd02e-e3cf-4275-ab7d-1ca22154bb42"),
                            Amount = 0.821765965699109m,
                            AssetId = new Guid("e8138054-fa82-41d6-8151-a0beae0e9ce3"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6157)
                        },
                        new
                        {
                            Id = new Guid("e49a5e46-b1d7-444b-a192-a30d4566ee09"),
                            Amount = 0.936476256668789m,
                            AssetId = new Guid("9ae88eb3-6566-4bc9-a324-d2f02be4fe97"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6177)
                        },
                        new
                        {
                            Id = new Guid("981c66c7-2dc1-47c2-85bd-f88d9c2eef14"),
                            Amount = 0.897454203524373m,
                            AssetId = new Guid("11f8fdde-907b-4789-bfc4-4c957863cf08"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6196)
                        },
                        new
                        {
                            Id = new Guid("6e206ae3-53f1-47a4-a044-16f18ec926ec"),
                            Amount = 0.124092500248967m,
                            AssetId = new Guid("bc4e06fe-7a90-4b59-958a-1c3c1aebe354"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6215)
                        },
                        new
                        {
                            Id = new Guid("f687f184-c6be-468f-97d5-4c4d559c54db"),
                            Amount = 0.635036762633844m,
                            AssetId = new Guid("ae4ca653-cc94-4b79-90f6-3cd3da759bf7"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6234)
                        },
                        new
                        {
                            Id = new Guid("24fbae34-ccf6-4996-b787-bfa5e421dd4d"),
                            Amount = 0.425046026438962m,
                            AssetId = new Guid("ecceeaed-787c-4750-bb40-f5d517e5c3db"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6294)
                        },
                        new
                        {
                            Id = new Guid("52557bad-9f18-4aaa-b99d-9dc5a932f41f"),
                            Amount = 0.578589509976371m,
                            AssetId = new Guid("c34312b6-0d0f-4ef7-b41f-dc8452416b69"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6313)
                        },
                        new
                        {
                            Id = new Guid("bb765a8c-91aa-4a28-a432-7a35773a54a5"),
                            Amount = 0.75576456857648m,
                            AssetId = new Guid("df8a6e5e-f402-462b-976c-9d307ec12ee7"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6335)
                        },
                        new
                        {
                            Id = new Guid("28c9042c-7b0e-4b5f-b11f-eab2008ac229"),
                            Amount = 0.690572485183632m,
                            AssetId = new Guid("69c6d469-00f8-4f28-9f04-f7e17df4f5f7"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6354)
                        },
                        new
                        {
                            Id = new Guid("48819415-3d2d-4f33-a2d2-09c588f594c3"),
                            Amount = 0.603381159996326m,
                            AssetId = new Guid("78c7348d-88ff-41f0-8259-0d97675a5f9c"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6374)
                        },
                        new
                        {
                            Id = new Guid("024b7fa2-37ac-4441-8849-6c2055ab33f2"),
                            Amount = 0.944188711673109m,
                            AssetId = new Guid("e9ccf1cd-714a-405e-bf7d-4924693e80fb"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6393)
                        },
                        new
                        {
                            Id = new Guid("b03859a7-3832-43a9-99fa-8af8334b887b"),
                            Amount = 0.996493846176422m,
                            AssetId = new Guid("7aae3717-f242-43b2-a74a-50dc23a1b355"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6414)
                        },
                        new
                        {
                            Id = new Guid("44dc5b0e-0ed9-48c4-b237-b6dc27d276ab"),
                            Amount = 0.78705709697076m,
                            AssetId = new Guid("f3583cf4-e20f-4eae-8740-e47074979b1d"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6433)
                        },
                        new
                        {
                            Id = new Guid("ba1c0e08-c495-45c9-b769-629e275f50d1"),
                            Amount = 0.888238636259101m,
                            AssetId = new Guid("0ea9e1f1-4c0c-4bfa-875a-d31750df7414"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6454)
                        },
                        new
                        {
                            Id = new Guid("a6da231d-7aaa-465f-a4ab-d31429ce33b1"),
                            Amount = 0.528248491942998m,
                            AssetId = new Guid("83a5f742-d236-4dae-8aad-74ad63af0433"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6477)
                        },
                        new
                        {
                            Id = new Guid("d9098e12-df53-4e7d-8835-9a821ad6c4bf"),
                            Amount = 0.167315946504155m,
                            AssetId = new Guid("1180a574-d677-49e9-9109-bc5492e60ca4"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6499)
                        },
                        new
                        {
                            Id = new Guid("2c270bf7-644c-476f-b0a7-e7cb34137c5e"),
                            Amount = 0.280203755144125m,
                            AssetId = new Guid("7245285b-415c-497f-8e05-46601832d5a6"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6518)
                        },
                        new
                        {
                            Id = new Guid("334f8c8f-d690-4eb0-81b9-f451e5a9a1e9"),
                            Amount = 0.990569157987167m,
                            AssetId = new Guid("91d62eae-5a19-406f-914d-84feb1e5f182"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6538)
                        },
                        new
                        {
                            Id = new Guid("18328327-5568-4ba5-a191-cabae1e7026f"),
                            Amount = 0.722459453494502m,
                            AssetId = new Guid("23dcddec-ea26-4ac2-a0f0-4ee19293d71c"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6557)
                        },
                        new
                        {
                            Id = new Guid("3141c810-8aa7-4524-824a-058f7728017d"),
                            Amount = 0.572106967480903m,
                            AssetId = new Guid("ca8d21c5-e52f-4332-a334-1cf88f33c8ad"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6577)
                        },
                        new
                        {
                            Id = new Guid("8d8825f5-838a-4b61-bbaf-6c8309feeea3"),
                            Amount = 0.888253568153946m,
                            AssetId = new Guid("e8138054-fa82-41d6-8151-a0beae0e9ce3"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6598)
                        },
                        new
                        {
                            Id = new Guid("db1d8806-0ae2-4eca-94fa-c83d65600352"),
                            Amount = 0.302197379200811m,
                            AssetId = new Guid("9ae88eb3-6566-4bc9-a324-d2f02be4fe97"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6617)
                        },
                        new
                        {
                            Id = new Guid("3ce1fb3a-1c14-46be-a036-d129578a3410"),
                            Amount = 0.436602003144381m,
                            AssetId = new Guid("11f8fdde-907b-4789-bfc4-4c957863cf08"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6637)
                        },
                        new
                        {
                            Id = new Guid("3b994310-1344-462c-9085-2e2e6f6a1911"),
                            Amount = 0.453236327717656m,
                            AssetId = new Guid("bc4e06fe-7a90-4b59-958a-1c3c1aebe354"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6659)
                        },
                        new
                        {
                            Id = new Guid("64d700be-2272-416a-b14b-877f69b8f061"),
                            Amount = 0.567934433728426m,
                            AssetId = new Guid("ae4ca653-cc94-4b79-90f6-3cd3da759bf7"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6678)
                        },
                        new
                        {
                            Id = new Guid("06aa4b25-1fdb-4e3c-b52a-815ebf6ced52"),
                            Amount = 0.485155759605186m,
                            AssetId = new Guid("ecceeaed-787c-4750-bb40-f5d517e5c3db"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6698)
                        },
                        new
                        {
                            Id = new Guid("c6e6ec09-2487-461d-a656-0af03e045dd0"),
                            Amount = 0.885307124296812m,
                            AssetId = new Guid("c34312b6-0d0f-4ef7-b41f-dc8452416b69"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6717)
                        },
                        new
                        {
                            Id = new Guid("1afd0748-f91a-4046-8cd4-370676295c6d"),
                            Amount = 0.781967277537085m,
                            AssetId = new Guid("df8a6e5e-f402-462b-976c-9d307ec12ee7"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6736)
                        },
                        new
                        {
                            Id = new Guid("314beccb-01e8-46c9-945d-3ec1d52a4dc0"),
                            Amount = 0.100357300648632m,
                            AssetId = new Guid("69c6d469-00f8-4f28-9f04-f7e17df4f5f7"),
                            CategoryId = new Guid("bba4892d-aa7d-48cd-b993-7c6c4ad7795b"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Id = new Guid("d1c0ef6a-a4e8-482d-becd-3d062637ecfb"),
                            Amount = 0.565485076776466m,
                            AssetId = new Guid("78c7348d-88ff-41f0-8259-0d97675a5f9c"),
                            CategoryId = new Guid("21c24ee8-400f-425f-827f-3a5a63cfc41a"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6775)
                        },
                        new
                        {
                            Id = new Guid("c1506e49-cf77-4c6d-953a-de4eae0ec136"),
                            Amount = 0.47761610545107m,
                            AssetId = new Guid("e9ccf1cd-714a-405e-bf7d-4924693e80fb"),
                            CategoryId = new Guid("4465055f-f51c-4eab-8a9e-00381104b17f"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6795)
                        },
                        new
                        {
                            Id = new Guid("39d9983a-d52a-45c7-8f5d-c4b2e99282e4"),
                            Amount = 0.0189952887683154m,
                            AssetId = new Guid("7aae3717-f242-43b2-a74a-50dc23a1b355"),
                            CategoryId = new Guid("0fc0895e-3770-4751-b418-8214dd05fdb2"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6817)
                        },
                        new
                        {
                            Id = new Guid("e558e5b6-756a-4655-9e27-1419e33ed8ef"),
                            Amount = 0.397217169588998m,
                            AssetId = new Guid("f3583cf4-e20f-4eae-8740-e47074979b1d"),
                            CategoryId = new Guid("9b7883e9-748b-43f6-836d-8d45e0fe8728"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6837)
                        },
                        new
                        {
                            Id = new Guid("f5989e75-6bf9-49b7-8c7c-14056351c25b"),
                            Amount = 0.209564393949492m,
                            AssetId = new Guid("0ea9e1f1-4c0c-4bfa-875a-d31750df7414"),
                            CategoryId = new Guid("00744991-0be3-49b1-a210-dfa198507abe"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6857)
                        },
                        new
                        {
                            Id = new Guid("ba2d05b2-5b7a-49e4-8e6a-1ea4312729fc"),
                            Amount = 0.286646054259802m,
                            AssetId = new Guid("83a5f742-d236-4dae-8aad-74ad63af0433"),
                            CategoryId = new Guid("1399213d-7895-42c8-9eca-48161c848d50"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6876)
                        },
                        new
                        {
                            Id = new Guid("ce79df20-08df-47d0-9a8f-1624d2148a48"),
                            Amount = 0.790492565739198m,
                            AssetId = new Guid("1180a574-d677-49e9-9109-bc5492e60ca4"),
                            CategoryId = new Guid("63ef9870-05cc-4658-a065-660c8f0d26f4"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6895)
                        },
                        new
                        {
                            Id = new Guid("14b92f0b-2be8-46a9-9404-f0bc2e94141e"),
                            Amount = 0.801668509282949m,
                            AssetId = new Guid("7245285b-415c-497f-8e05-46601832d5a6"),
                            CategoryId = new Guid("2c894af1-88c0-4ec4-881a-17c7fff4773c"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6919)
                        },
                        new
                        {
                            Id = new Guid("e3b41033-d308-4ed5-81ab-09ff06538835"),
                            Amount = 0.242325993833284m,
                            AssetId = new Guid("91d62eae-5a19-406f-914d-84feb1e5f182"),
                            CategoryId = new Guid("c8b61123-108e-4829-955a-06b6d6765f7d"),
                            Date = new DateTime(2020, 4, 1, 16, 23, 58, 383, DateTimeKind.Local).AddTicks(6939)
                        });
                });

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12e7dc3a-1b52-4811-a848-1e748168db53"),
                            Email = "PVQS9JY",
                            Hash = "59CP5IO",
                            Name = "INLM3CM",
                            Salt = "UJMWRZF"
                        },
                        new
                        {
                            Id = new Guid("0c072651-0a8c-4819-82be-03f91183934e"),
                            Email = "UM5DK9P",
                            Hash = "NS3YCHK",
                            Name = "TVAJFSS",
                            Salt = "TZB6S9P"
                        },
                        new
                        {
                            Id = new Guid("093d4313-7992-42f6-85c3-8a15e3ccbd2b"),
                            Email = "RFKCBJM",
                            Hash = "0GWED1U",
                            Name = "HM9PHNB",
                            Salt = "8FFTW1L"
                        },
                        new
                        {
                            Id = new Guid("10a43690-3d99-48bf-894a-2fbdc4296ad8"),
                            Email = "QP3LN7O",
                            Hash = "Q9WCV2D",
                            Name = "65EOH2J",
                            Salt = "72XL7YD"
                        },
                        new
                        {
                            Id = new Guid("e68808ab-20fa-4191-ad88-f662ec6fb9da"),
                            Email = "9PNPVIT",
                            Hash = "LYJE831",
                            Name = "TRT5PZB",
                            Salt = "THPI47E"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Asset", b =>
                {
                    b.HasOne("DataAccess.Models.User", null)
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("DataAccess.Models.Asset", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.Category", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
